//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class alumno
    {
        public int alumnoID { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Edad { get; set; }
        public string fecha_de_nacimiento { get; set; }
        public string Correo { get; set; }
        public string Sede { get; set; }
        public Nullable<int> telefono { get; set; }
        public string Carnet { get; set; }
        public string Curso { get; set; }
        public Nullable<int> Nota_final { get; set; }
    }
}
